DROP TABLE IF EXISTS credit_default;

CREATE TABLE credit_default(
	id INT PRIMARY KEY,
	LIMIT_BAL NUMERIC,
	SEX INT,
	EDUCATION INT,
	MARRIAGE INT,
	AGE INT,
	PAY_0 INT,
	PAY_2 INT,
	PAY_3 INT,
	PAY_4 INT,
	PAY_5 INT,
	PAY_6 INT, 
	BILL_AMT1 NUMERIC,
	BILL_AMT2 NUMERIC,
	BILL_AMT3 NUMERIC,
	BILL_AMT4 NUMERIC,
	BILL_AMT5 NUMERIC,
	BILL_AMT6 NUMERIC,
	default_payment_next_month INT
);
